name: Cleanup Artifacts
on:
  schedule:
    - cron: '0 0 * * *' # 每天运行一次
  workflow_dispatch:    # 支持手动触发

permissions:
  actions: write
  contents: read

jobs:
  cleanup_releases:
    runs-on: ubuntu-latest
    name: 清理发布任务 (保留最新2个)
    steps:
      - name: Delete old release artifacts
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          # 指定你的发布 Workflow 文件名
          workflow: release.yml

          # 保留策略
          retain_days: 0       # 过期天数设为0 (完全由下面数量控制)
          keep_minimum_runs: 2 # 无论过期与否，死保最新的 2 个

  cleanup_cdn:
    runs-on: ubuntu-latest
    name: 分析任务 (只保留最新1个)
    steps:
      - name: Delete old CI artifacts
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          workflow: ci.yml

          retain_days: 0
          keep_minimum_runs: 1
